# Themelios configuration.sh

use_sgdisk_clear="true"
use_wipefs_all="true"
use_zero_disks="false"
zfs_encrypt_home="true"
zfs_pool_name="z620pool"
zfs_pool_type="mirror"
zfs_pool_disks=("/dev/disk/by-id/ata-KINGSTON_SA400S37120G_50026B77820D2629"
                "/dev/disk/by-id/ata-KINGSTON_SA400S37120G_50026B77820D2E9A")
zfs_auto_snapshot=("$zfs_pool_name/HOME" "$zfs_pool_name/ROOT")
nix_top_level_configuration="hosts/Z620"
nix_repo_name="nix-config"
nix_zfs_configuration_extra_enabled="true"
nix_zfs_extra_auto_scrub="true"
nix_zfs_extra_auto_snapshot_enabled="true"
nix_zfs_extra_auto_snapshot_frequent="8"
nix_zfs_extra_auto_snapshot_hourly="24"
nix_zfs_extra_auto_snapshot_daily="0"
nix_zfs_extra_auto_snapshot_weekly="0"
nix_zfs_extra_auto_snapshot_monthly="0"
nix_zfs_extra_auto_optimise_store="true"
nix_zfs_extra_gc_automatic="true"
nix_zfs_extra_gc_dates="weekly"
nix_zfs_extra_gc_options="--delete-older-than 7d"
nix_zfs_extra_clean_tmp_dir="true"
